spring.application.name=catalog-service
#spring.config.import=optional:configserver:


logging.level.org.springframework.level=INFO
logging.level.root=DEBUG

# HTTP Client Timeouts
http.connectTimeout=2000
http.readTimeout=10000
http.url=http://www.google.com/mcssapi-501/rp-webapp-9-common

