spring.application.name=catalog-service
#logging.level.org.springframework.cloud.config.client=DEBUG
#logging.level.org.springframework.amqp=DEBUG
#logging.level.org.springframework.cloud.bus=DEBUG
logging.level.root=INFO
#spring.rabbitmq.ssl.enabled=true
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=cat
