spring.application.name=catalog-service
app.property=hello
spring.config.import=optional:configserver:

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

logging.level.org.springframework.level=INFO
logging.level.root=INFO

jasypt.encryptor.algorithm=PBEWITHHMACSHA512ANDAES_256
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.RandomIvGenerator
jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD}
