spring.application.name=catalog-service
app.property=hello
#spring.config.import=optional:configserver:
spring.profiles.active=local
# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

logging.level.org.springframework.level=INFO
logging.level.root=INFO


